name: Build
on:
  push:
    branch: 'master'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type: [debug, release]
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: build ${{ matrix.type }}
      run: make TYPE=${{ matrix.type }}
